# Generated by Django 5.1.3 on 2024-11-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0003_produkt_kategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='surowiec',
            name='kategoria',
            field=models.CharField(choices=[('napoje', 'napoje'), ('warzywa', 'warzywa'), ('owoce', 'owoce'), ('mięso', 'mięso'), ('nabiał', 'nabiał'), ('pieczywo', 'pieczywo')], default='posiłki', max_length=64),
        ),
    ]
