# Generated by Django 5.1.3 on 2024-11-16 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0004_surowiec_kategoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recenzja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocena', models.IntegerField()),
                ('opis', models.TextField()),
                ('data_wpisu', models.DateTimeField(auto_now_add=True)),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jedzonko.produkt')),
            ],
        ),
    ]
