# Generated by Django 5.1.3 on 2024-11-16 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0005_recenzja'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recenzja',
            options={'verbose_name': 'Recenzja', 'verbose_name_plural': 'Recenzje'},
        ),
    ]
